# Generated by Django 3.2.16 on 2022-11-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_sport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='weekday',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='sportsclub',
            constraint=models.UniqueConstraint(fields=('city', 'address'), name='unique_club'),
        ),
    ]
