# Generated by Django 3.2.16 on 2022-11-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20221111_2238'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sportsclub',
            name='unique_club',
        ),
        migrations.RemoveField(
            model_name='sportsclub',
            name='club_logo',
        ),
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='sport_avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='sports_avatars'),
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='club_avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='clubs_avatars'),
        ),
        migrations.AddConstraint(
            model_name='sportsclub',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_club'),
        ),
    ]
