# Generated by Django 3.2.16 on 2022-11-16 00:19

import club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20221112_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['sport']},
        ),
        migrations.RemoveField(
            model_name='sportsclub',
            name='club_avatar',
        ),
        migrations.AddField(
            model_name='sportsclub',
            name='sports_club_avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=club.models.photo_path),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=club.models.photo_path),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=club.models.photo_path),
        ),
    ]
